spring:
 application:
  name: haoke-config

 cloud:
  config:
   label: master
   server:
    git:
     uri: https://
     search-paths: respo
     username:
     password:

server:
 port: 8888

eureka:
 client:
   serviceUrl:
      defaultZone: http://localhost:8061/eureka/

spring:
 zipkin:
  base-url: http://localhost:8076/

