spring:
 application:
   name: haoke-service-pay
 zipkin:
  base-url: http://localhost:8076/
 boot:
     admin:
      client:
       url: http://localhost:8077

 thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
server:
   port: 8079

feign:
  hystrix:
    enabled: true



eureka:
 client:
   serviceUrl:
      defaultZone: http://localhost:8061/eureka/

